---
- name: "Install dependencies: {{ APP_DEPENDENCIES | join(' ') }}"
  shell: "pkcon install -y {{ item }}"
  loop: "{{ APP_DEPENDENCIES }}"
  ignore_errors: true
- name: "Create the directory {{ APP_SRC }}"
  file:
    name: "{{ APP_SRC }}"
    state: directory
- name: "Check for the README file {{ APP_README }}"
  stat:
    path: "{{ APP_README }}"
  register: APP_README_PATH
- name: "Clone the {{ APP_REPO }} source code into {{ APP_SRC }}"
  git:
    repo: "{{ APP_REPO }}"
    dest: "{{ APP_SRC }}"
    version: "{{ APP_TAG }}"
  when: not APP_README_PATH.stat.exists
- name: "Run the meson build script in {{ APP_SRC }}"
  shell:
    cmd: "(export PKG_CONFIG_PATH={{ APP_PREFIX }}/lib/pkgconfig && meson build --prefix {{ APP_PREFIX }})"
    chdir: "{{ APP_SRC }}"
- name: "Run the ninja build script in {{ APP_SRC }}"
  shell:
    cmd: "(export PKG_CONFIG_PATH={{ APP_PREFIX }}/lib/pkgconfig && ninja -C build)"
    chdir: "{{ APP_SRC }}"
- name: "Run the ninja build install script in {{ APP_SRC }}"
  shell:
    cmd: "(export PKG_CONFIG_PATH={{ APP_PREFIX }}/lib/pkgconfig && ninja -C build install)"
    chdir: "{{ APP_SRC }}"
- name: "Create the launcher {{ APP_DESKTOP }}"
  template:
    src: app.desktop
    dest: "{{ APP_DESKTOP }}"
    mode: "0775"

